name = "atteny"
main = "./build/worker.js"
compatibility_date = "2024-04-01"

[env.production]
name = "atteny-production"
route = "atteny.popok.uk/*"

[vars]
PUBLIC_PB_URL="http://127.0.0.1:8090"
PUBLIC_UNIT_PRICE=5
PUBLIC_FREE_TIER=5
# google
PUBLIC_GOOGLE_CLIENT_ID='530631853241-d9bm5q01d2kbc158t3od6oo5ga389j1r.apps.googleusercontent.com'
PUBLIC_GOOGLE_PROJECT_NUMBER='530631853241'