name = "atteny"
main = "./build/worker.js"
compatibility_date = "2024-04-01"

[env.production]
name = "atteny-prod"
route = "atteny.popok.uk/*"

[assets]
directory = ".svelte-kit/output/"
binding = "ASSETS"