name = "atteny"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-04-01"
route = "atteny.popok.uk/*"

[build.upload]
format = "modules"
main = "./.svelte-kit/cloudflare/worker.js"

[assets]
directory = ".svelte-kit/output/"
binding = "ASSETS"